//
// Created by outfrost on 03/04/17.
//

#include <stdexcept>
#include "string_consts.h"

#ifndef DATA_STRUCTURES_PROJECT_BINARYHEAP_H
#define DATA_STRUCTURES_PROJECT_BINARYHEAP_H 0

#define BINARYHEAP_MIN_OVERHEAD 4
#define BINARYHEAP_MAX_OVERHEAD 32
#define BINARYHEAP_TARGET_OVERHEAD 16

#if (BINARYHEAP_MIN_OVERHEAD > BINARYHEAP_MAX_OVERHEAD)
#error "BINARYHEAP_MIN_OVERHEAD must not be larger than BINARYHEAP_MAX_OVERHEAD"
#endif

#if (BINARYHEAP_TARGET_OVERHEAD < BINARYHEAP_MIN_OVERHEAD || BINARYHEAP_TARGET_OVERHEAD > BINARYHEAP_MAX_OVERHEAD)
#error "BINARYHEAP_TARGET_OVERHEAD must have a value between BINARYHEAP_MIN_OVERHEAD and BINARYHEAP_MAX_OVERHEAD, inclusive"

#endif //DATA_STRUCTURES_PROJECT_BINARYHEAP_H
