//
// Created by outfrost on 03/04/17.
//

#ifndef DATA_STRUCTURES_PROJECT_LINKEDLISTELEMENT_H
#define DATA_STRUCTURES_PROJECT_LINKEDLISTELEMENT_H

#endif //DATA_STRUCTURES_PROJECT_LINKEDLISTELEMENT_H
